#' Plot mb.ecors object
#'
#' Plot MapBiomas images processed by get.mb.ecors along with site and sample polygons.
#'
#' @param x mb.ecors object (from get.mb.ecors).
#' @param comp mb.ecors object generated by focal.mb.ecors function or ecors object (remote sensing) used for comparison (optional).
#' @param zoom initial zoom value.
#' @param legend choose to show the legend or not.
#'
#' @return
#' Google Earth Engine containers objects are exported to .GlobalEnv to be used in rgee functions and avoid errors (elapsed time limit):
#' \itemize{
#' \item map.samples: sample polygons (evaluation carried out in the surroundings of these polygons),
#' \item map.site: site polygon (evaluation carried out in the surroundings of this polygon),
#' \item map.polygons: polygon for land use evaluation (evaluation carried out inside these polygons),
#' \item map.buffer(i): polygons of buffer areas (if selected in get.mb.ecors);
#' \item map.mb(i): plot object of a raster image (one object per image),
#' \item leg.mb: legend.}
#'
#' @export
#' @import rgee
#' @import googledrive
#' @import sf
#' @import dplyr
#'
#' @examples
#' #Get a mb.ecors class object
#' FAL.IBGE.JBB<-sf::st_read(system.file("extdata/FAL.IBGE.JBB.gpkg", package="ecors"))
#' test.points<-sf::st_read(system.file("extdata/Points_tests.gpkg", package="ecors"))
#' test.retangles<-sf::st_read(system.file("extdata/Plots_tests.gpkg", package="ecors"))
#'
#' # Get data (projecting to UTM 32S zone to performe buffer operations)
#' mb2000_2010<-get.mb.ecors(site=FAL.IBGE.JBB, points=test.points, plots=test.retangles,
#'      polygons=NULL, id.column=1, projected=F, custom.crs=32723,
#'      collection.mb=6, years=c(2000,2010), resolution=30, evaluate="surroundings.site",
#'      buffer1=5000, buffer2=10000, buffer3=NULL, cumulative.surroundings=F)
#'
#' #Plotting
#' plot(x=mb2000_2010)

plot.mb.ecors<-function(x,comp=NULL,zoom=12,legend=T){

  if(class(x)!="mb.ecors"){stop("Argument x must be a mb.ecors class object.")}

  mb.prov<-eval(parse(text=x$object.name))


  if(is.null(comp)==F){if(class(comp)!="mb.ecors" & class(comp)!="ecors"){stop("Argument comp must be a ecors or mb.ecors class object.")}
    if(class(comp)=="mb.ecors"){
      if(comp$post.processing=="none"){stop("Argument comp with a mb.ecors class object needs to be generated by focal.mb.ecors function.")}
    }
  }

  #To get center
  if(x$evaluate=="surroundings.site"){center.poly.transf<-x$site.gee$geometry(1)$transform()}
  if(x$evaluate=="surroundings.samples"){center.poly.transf<-x$samples.gee$geometry(1)$transform()}
  if(x$evaluate=="inside.polygons"){center.poly.transf<-x$polygons.gee$geometry(1)$transform()}

  center<-center.poly.transf$centroid()$getInfo()$coordinates #esse comando é incompatível com UTM

  Map$setCenter(center[1],center[2],zoom)
  comando.visuali<-c()
  comando.visualiB<-c()

  for (i in 1:length(x$years)){
    par.vis.mb<-list(palette=x$palette.mb$color,values=x$palette.mb$lu.class,bands=paste0("classification_",x$years[i]),min=0,max=max(x$palette.mb$pixel.value))
    prov<-Map$addLayer(mb.prov,par.vis.mb,paste0(x$years[i]))
    assign(paste0("map.mb",i),prov,envir=.GlobalEnv)
    if(length(comando.visuali)==0){comando.visuali<-c("map.mb1")} else {
      comando.visuali<-paste0(comando.visuali,"+map.mb",i)}

    if(is.null(comp)==F){
      if(class(comp)=="mb.ecors"){
        mb.f<-eval(parse(text=comp$object.name))
        prov.f<-Map$addLayer(mb.f,par.vis.mb,paste0(x$years[i],comp$post.processing[length(comp$post.processing)]))
        assign(paste0("map.mb.f",i),prov.f,envir=.GlobalEnv)
        if(length(comando.visualiB)==0){comando.visualiB<-c("map.mb.f1")} else {
          comando.visualiB<-paste0(comando.visualiB,"+map.mb.f",i)}
      }
    }
  }

  #different number of images here (separated loop)
  if(is.null(comp)==F){
    if(class(comp)=="ecors"){
      vpar<-comp$d.vpar
      colle.plot<-colle.filt

      if(is.null(comp$d.vpar$reescalonar)==F){
        multiplica<-comp$vpar$reescalonar$multiplica #list '$' is incompatible with map functions
        soma<-comp$vpar$reescalonar$soma
        vpar<-within(comp$vpar,rm(reescalonar))
        FUNreescalonar<-function(imagem){imagem$multiply(multiplica)$add(soma)}
        colle.plot<-colle.plot$map(FUNreescalonar)
      }

      for (i in 1:nrow(comp$images.table)){
        prov.sat<-Map$addLayer(colle.plot[[i]],comp$vpar,as.character(comp$images.table$OKdates[i]))
        assign(paste0("img",i),prov.sat,envir=.GlobalEnv)
        if(length(comando.visualiB)==0){comando.visualiB<-c("img1")} else {
          comando.visualiB<-paste0(comando.visualiB,"+img",i)}
      }
    }
  }

  if(legend==T){
    leg.mb<<-Map$addLegend(par.vis.mb,name="Legend",color_mapping="character",position="topright")
    comando.visuali<-paste0(comando.visuali,"+leg.mb")
  }
  if(is.null(x$site.gee)==F){
    map.site<<-Map$addLayer(x$site.gee,name="site")
    comando.visuali<-paste0(comando.visuali,"+map.site")
  }
  if(is.null(x$samples.gee)==F){
    map.samples<<-Map$addLayer(x$samples.gee,name="samples")
    comando.visuali<-paste0(comando.visuali,"+map.samples")
  }
  if(is.null(x$polygons.gee)==F){
    map.polygons<<-Map$addLayer(x$polygons.gee,name="polygons")
    comando.visuali<-paste0(comando.visuali,"+map.polygons")
  }
  if(is.null(x$polig.mb1.gee)==F){
    map.buffer1<<-Map$addLayer(x$polig.mb1.gee,name="buffer1")
    comando.visuali<-paste0(comando.visuali,"+map.buffer1")
  }
  if(is.null(x$polig.mb2.gee)==F){
    map.buffer2<<-Map$addLayer(x$polig.mb2.gee,name="buffer2")
    comando.visuali<-paste0(comando.visuali,"+map.buffer2")
  }
  if(is.null(x$polig.mb3.gee)==F){
    map.buffer3<<-Map$addLayer(x$polig.mb3.gee,name="buffer3")
    comando.visuali<-paste0(comando.visuali,"+map.buffer3")
  }

  #comparing with focal
  if(is.null(comp)==F){
    comando.visuali<-paste0(comando.visuali,"|",comando.visualiB)

  }
  cat(comando.visuali)


  cat("\nOpening map in new window (eg browser) can improve visualization.\n")

  return(eval(parse(text=comando.visuali),envir=.GlobalEnv))
}
